### ISSUE TITLE
AOE - Savings Plans Usage | Workbook - Savings plan dropdown empty

### ISSUE THREAD

**Issue by psilantropy** [microsoft/finops-toolkit#1014] opened 2024-09-30 02:36 UTC
## 🐛 Problem
Quick one for next release :).
Savings plan drop down is empty due to parameter settings in the Savings Plans Usage | Workbook.

## 👣 Repro steps
My Savings Plan has Provisioning state = Expiring.
If I amend the workbook dropdown as below, my savings plan shows up.
`ProvisioningState_s == 'Expiring'\r\n`

Also verified the csv export to the storage account has the same ProvisioningState value.

Aggregator Tag does not populate after making the above change, so still another issue with the workbook based on this.
If I change aggregator tag required = false - the workbook now works a little bit more (only usage by tag)

## 🤔 Expected
Should see all savings plans in the drop down. More status options should allow the Savings plan drop down to populate.

## ❓  Additional Info
- Should other states also be included? Pending, , Expiring, Cancelled, Refunded, Expired (I'm guessing these status names).
- Does this issue also affect the Reservations workbook or others?

**Comment by helderpinto** [comment] 2024-09-30 07:51
Hi, @psilantropy. Thanks for the reporting this issue. 

Interestingly, "Expiring" is not in the [documented provisioning states](https://learn.microsoft.com/rest/api/billingbenefits/savings-plan/get?view=rest-billingbenefits-2022-11-01&tabs=HTTP#provisioningstate).

We have to check what are the current possible values and maybe reconsider which states are relevant for a usage analysis point of view. 

In the meantime, can you replace the workbook code by [this tentative fix](https://github.com/helderpinto/finops-toolkit/blob/helderpinto/dev/fix1014/src/optimization-engine/views/workbooks/savingsplans-usage.json) and confirm the issue is worked around?

You are right about the Reservations Usage workbook. It has the same problem and there's a similar fix available [here](https://github.com/helderpinto/finops-toolkit/blob/helderpinto/dev/fix1014/src/optimization-engine/views/workbooks/reservations-usage.json).

Regarding the Aggregator Tag parameter, it is a text field that you should populate yourself with the name of a tag that you want to use to aggregate your savings plans usage. For example, let's say you usually tag your Azure resources with a `costcenter` tag and you want to see how savings plans have been applied across the different cost centers.

**Comment by psilantropy** [comment] 2024-09-30 19:34
Hi @helderpinto 

Thanks for sorting. Your workbook provided fixed it. Tested Reservation one also and looks good.

Yes, I looked up the possible states too and that was not included - but it's definitely present. I only run 1 savings, plan but ~30 reservations and often have a few 'expiring' together for a few weeks. I can't find any other states not mentioned in the documentation.

Sorry I figured out the tag thing later. I just didn't expect it to be mandatory, so thought it was something else. Thanks 👍

**Comment by helderpinto** [comment] 2024-09-30 20:41
Thank you for confirming the fix, @psilantropy! This issue will be closed as soon as the fix PR is merged.

**Comment by psilantropy** [comment] 2024-10-01 00:38
Sorry - didn't see this before. Noticed another error;

Full Usage Report
`'project' operator: Failed to resolve scalar expression named 'ExpiryDate_t'...`

Unused Savings Plans Details
`'project' operator: Failed to resolve scalar expression named 'ExpiryDate_t'...`

**Closed** 2024-10-01 06:27 UTC
Labels: Type: Bug 🐛, Status: 📦 Pending release, Tool: Optimization Engine

**Comment by helderpinto** [comment] 2024-10-01 07:56
Hi, @psilantropy. Can you please open a new issue for the `ExpiryDate_t` column error? I guess this only shows up in the "Full Usage Report" and "Unused Savings Plans Analysis" tabs. Also, include whether you're on EA or MCA. Thanks.

**Comment by flanakin** [comment] 2024-10-02 04:19
@allcontributors Please add psilantropy for bug
