### ISSUE TITLE
PowerBI Report stays blank

### ISSUE THREAD

**Issue by guidovanbrakel** [microsoft/finops-toolkit#996] opened 2024-09-19 05:00 UTC
I have some issues with the PowerBI report from AzureOptimization, I have connected it to the Azure SQL Database which is created by the AzureOptimization. 
![image](https://github.com/user-attachments/assets/be147ae3-47f1-410c-bc2e-9d99349bc3d1)

Is there any detailed documentation how to fix this?

**Comment by helderpinto** [comment] 2024-09-19 16:42
Hi, @guidovanbrakel! Thanks for reporting this issue. 

As a start, please check the [FAQ](https://microsoft.github.io/finops-toolkit/optimization-engine/faq), particularly the "_Why are my Recommendations workbook and Power BI report still empty after deploying AOE?_" question.

Can you also check whether the `Recommendations` workbook is also empty?

**Comment by guidovanbrakel** [comment] 2024-09-19 16:48
I have tried but still no data

**Comment by guidovanbrakel** [comment] 2024-09-19 19:45
And @helderpinto the recommendations report is not empty

**Comment by helderpinto** [comment] 2024-09-19 20:58
@guidovanbrakel, if the `Recommendations` workbook is not empty, this means that everything should be fine upstream, and the only problem might be with the `Ingest-RecommendationsToSQLServer` runbook in the Azure automation account. Can you please check what was the result/output of its latest job?

**Comment by guidovanbrakel** [comment] 2024-09-20 05:06
@helderpinto the Ingest-RecommedationsToSqlServer has a status completed.

**Comment by guidovanbrakel** [comment] 2024-09-20 05:52
@helderpinto I got it working finally I was able to delete your data source

**Comment by helderpinto** [comment] 2024-09-20 08:16
Yes, you need to change the data source and refresh the report, as documented [here](https://microsoft.github.io/finops-toolkit/optimization-engine/reports#-power-bi-recommendations-report). Let me know if anything else is needed and if we can close this issue.

**Comment by guidovanbrakel** [comment] 2024-09-21 08:38
@helderpinto I got it working finally I was able to delete your data source.

Now all tabs are loading but the Cost Page. Do I have to connect the Azure Cost Management Connector in PowerBI for that?

**Comment by helderpinto** [comment] 2024-09-21 14:07
No, the Azure Cost Management Connector isn't needed. You should see in the Power BI Cost page the same cost recommendations you are able to see in the `Recommendations` workbook. Is there any difference between the amount of recommendations in Power BI and the workbook?

**Comment by guidovanbrakel** [comment] 2024-09-21 14:19
> No, the Azure Cost Management Connector isn't needed. You should see in the Power BI Cost page the same cost recommendations you are able to see in the `Recommendations` workbook. Is there any difference between the amount of recommendations in Power BI and in the workbook?

At the moment there no cost recommendationd

**Comment by helderpinto** [comment] 2024-09-21 14:27
This is an expected behavior, then. Your environment seems to be currently cost optimized, as far as both Azure Advisor and AOE can observe. If you installed recently AOE, allow it a couple weeks, because some recommendations are surfaced after enough historical data has been collected. 

I am closing this issue as resolved.

**Closed by helderpinto** 2024-09-21 14:27 UTC
Labels: Type: Bug 🐛, Status: 📋 Pending confirmation, Tool: Optimization Engine
