### ISSUE TITLE
Azure Optimization Engine Benefits Usage workbook error in Reservation usage vs. On-Demand prices: 'where' operator: Failed to resolve table or column expression named 'AzureOptimizationPricesheetV1_CL

### ISSUE THREAD

**Issue by kevinrosal** [microsoft/finops-toolkit#1129] opened 2024-11-15 22:09 UTC
## 🐛 Problem
After deploying AOE and following the steps on Enabling Azure commitments workbooks as said on this doc: https://microsoft.github.io/finops-toolkit/optimization-engine/setup-options 
i still receive the error as shown on the screenshots below.
This ticket https://github.com/microsoft/finops-toolkit/issues/995 talks about that AzureOptimizationPricesheetV1_CL Log Analytics table to be populated by the Export-PriceSheetToBlobStorage runbook and i was able to run that particular runbook successfully but the Table is still not present on the log analytics workspace.

## 👣 Repro steps
1. Go to Benefits Usage Workbook
2. Click on Open Workbook
3. Switch to "Reservations" Tab
4. Error appears on "Reservation usage vs. On-Demand prices" and "Reservation usage vs. Savings Plan prices"

## 🤔 Expected
To show information about reservations usage vs on-demand prices and reservations usage vs savings plan prices

## 📷 Screenshots
Giving access to our MCA and Billing profile
![Image](https://github.com/user-attachments/assets/bde8fbf6-aba8-47fa-a5d6-15317a211b20)

Workbook Error
![Image](https://github.com/user-attachments/assets/2bc3cbb1-b613-424f-bd1f-81ab52acd894)

## ℹ️ Additional context
This is an MCA agreement with a tenant that has 17 subscriptions.

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by helderpinto** [comment] 2024-11-16 11:53
Thank you for reporting this issue @kevinrosal and for the details shared. 

Can you run the `Ingest-OptimizationCSVExportsToLogAnalytics` runbook by passing `pricesheetexports` as value for the `StorageSinkContainer` parameter? If the job succeeds, you just have to wait 10-15 minutes before checking the `Benefits Usage` workbook again.

This logic runs automatically on a weekly basis and you should not see this error anymore after the first successful run.

**Comment by kevinrosal** [comment] 2024-11-18 17:15
@helderpinto that particular runbook has been running successfully every hour it looks like by default

![Image](https://github.com/user-attachments/assets/e64de775-9fe0-43a6-944f-bac7bf2995ec)

When i checked the workbook, it is still getting the same error about AzureOptimizationPricesheetV1_CL

**Comment by helderpinto** [comment] 2024-11-18 17:40
@kevinrosal, the above runbook is not exclusive to the `AzureOptimizationPricesheetV1_CL` table. It is used by all other AOE tables. The problem is, for pricesheet data, this runbook is scheduled to run only once per week and it might not have run after you granted the required permissions to AOE. Did you try to run it manually, as I suggested?

**Comment by kevinrosal** [comment] 2024-11-18 18:18
@helderpinto thanks for clarifying, i have ran the runbook manually and passed the value for StorageSinkContainer parameter and it ran successfully. i checked the benefits usage workbook after 10-15mins and still getting the same error

**Comment by kevinrosal** [comment] 2024-11-18 21:35
@helderpinto the job outputs look to be different on my end, see screenshot below
![Image](https://github.com/user-attachments/assets/62673ea0-bd22-4b4d-a013-58e8328f5a1f)
the Log Analytics Workspace doesnt have a daily cap. as for the AzureOptimization_PriceSheetMeterRegions variable. here is whats defined on my end
![Image](https://github.com/user-attachments/assets/88dd2277-6182-48c4-b4da-20819bf6dbc3)

**Comment by helderpinto** [comment] 2024-11-18 21:41
The job output you shared is for a different Storage container (`azmonitorexports`). You should look for the output of the job that had `pricesheetexports` as input.

Anyways, it seems the reason for not getting any rows in the pricesheet table is the regions you configured for the `AzureOptimization_PriceSheetMeterRegions` variable. You should use `CA Central` and `CA East` instead (pricesheet regions format). After fixing the regions values, can you please re-run the following runbooks?

- `Export-PriceSheetToBlobStorage`
- `Ingest-OptimizationCSVExportsToLogAnalytics` with `pricesheetexports` as value for the `StorageSinkContainer` parameter

**Comment by kevinrosal** [comment] 2024-11-18 22:14
@helderpinto that worked!! thank you for the assistance. after making the changes on the variable and re-running both runbooks the workbook is now working properly!

**Comment by helderpinto** [comment] 2024-11-19 08:22
Thanks for the feedback, @kevinrosal. Glad it worked. I am closing the issue as solved.

**Closed by helderpinto** 2024-11-19 08:22 UTC
Labels: Type: Bug 🐛, Status: 🕵️‍♀️ Investigating, Tool: Optimization Engine
