### ISSUE TITLE
Deployment template validation failed error

### ISSUE THREAD

**Issue by lundejd** [microsoft/finops-toolkit#593] opened 2024-02-07 20:56 UTC
Problem: Upon deployment we get a status "conflict" with an error: {"code":"DeploymentFailed","target":"/subscriptions/*******/resourceGroups/ITS-FINOPSTOOLKIT-001-P/providers/Microsoft.Resources/deployments/hub","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '/add' for type 'Microsoft.KeyVault/vaults/accessPolicies' at line '1' and column '3489' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":3489,"path":"properties.template.resources[0].type"}}]}]}

Steps to reproduce:

Browse to https://microsoft.github.io/finops-toolkit/hubs#-create-a-new-hub

Click Deploy to Azure

Answer questions then submit. The deployment will begin, run for a few minutes then hub errors out.

A data factory, storage account, managed identity and deployment script all are in the previously empty resource group. (we tried first with an existing RG that had a few things in it, then created a new empty RG so we could tell what was being build-out)

<img width="1805" alt="Screenshot 2024-02-07 at 2 04 15 PM" src="https://github.com/microsoft/finops-toolkit/assets/8152933/ac7a6aa7-de61-458c-91de-f269d929689a">
<img width="1813" alt="Screenshot 2024-02-07 at 2 04 00 PM" src="https://github.com/microsoft/finops-toolkit/assets/8152933/559efd85-9b36-498f-8efd-9a189b7a2d81">

Person deploying has full rights to all of Azure.

**Comment by arthurclares** [comment] 2024-02-08 09:23
We are aware of this issue. Please, start the deployment from scratch and use this release candidate instead: https://aka.ms/finops/hubs/rc

**Comment by erose96** [comment] 2024-03-04 22:18
@arthurclares any update on this issue / plan to update the docs to point towards the RC? been fighting most of the afternoon with these same deployment errors

**Comment by madhavjaya** [comment] 2024-03-05 09:21
I have tried couple of installations today and I get the same error even after using the following release candidate instead: https://aka.ms/finops/hubs/rc

**Comment by erose96** [comment] 2024-03-05 13:13
@madhavjaya I was able to get the RC to work using a new existing resource group, if you haven't maybe try that workflow

**Comment by flanakin** [comment] 2024-03-18 09:30
@lundejd / @madhavjaya, are y'all able to validate the RC is working as expected for you? We're hoping to get this out this week. We've hit a few delays due to time constraints.

**Comment by madhavjaya** [comment] 2024-03-18 09:32
Hi Michael,

Yes I can confirm the RC worked for me without any issues.

Regards
Maddy

**Comment by arthurclares** [comment] 2024-03-28 14:14
This is fixed on the newly released version 0.3

**Closed by arthurclares** 2024-03-28 14:14 UTC
Labels: Type: Bug 🐛, Status: ✅ Released, Solution: FinOps hubs
