### ISSUE TITLE
Error to Connect the report

### ISSUE THREAD

**Issue by paragbhardwaj1981** [microsoft/finops-toolkit#693] opened 2024-04-22 00:38 UTC
## 🐛 Problem
When i put my EA Number and not able to fetch the data. It is Saying Cost Detail "Access to the resource is forbidden". I have follow all the instruction and having the same issue. I have full rights on my Azure Cloud. 

## 👣 Repro steps
TODO: Add repro steps below:
1. Go to
2. Click on
3. Scroll down to

## 🤔 Expected
I am expecting that i will be able to connect my Cost through finops toolkit. I have already setup all the infrastucture.

<img width="1170" alt="image" src="https://github.com/microsoft/finops-toolkit/assets/71142051/ae8ab99e-cecf-458d-8e6c-4e1758f9f6d7">

## 📷 Screenshots
<img width="1298" alt="image" src="https://github.com/microsoft/finops-toolkit/assets/71142051/267461af-d82d-475a-b646-3f229f838db0">

## 🙋‍♀️ Ask for the community

We could use your help:
1. Please vote this issue up (👍) to prioritize it.
2. Leave comments to help us solidify the vision.

**Comment by paragbhardwaj1981** [comment] 2024-04-22 00:39
Please Provide your solution

**Comment by paragbhardwaj1981** [comment] 2024-04-30 02:38
Hi Team,

Can you please provide the feedback to me.

Thanks
Parag

**Comment by devisaladi** [comment] 2024-05-01 19:23
@flanakin  AnyUpdate . Appreciate if we have soltuion

**Comment by radut227** [comment] 2024-05-03 07:48
Dear Team
Facing the same issue with Cost Detail "Access to the resource is forbidden".

Any pointers?
Regards
Rahul

**Comment by arthurclares** [comment] 2024-05-14 07:08
@paragbhardwaj1981 Can you please make sure the account used in the login has the role "[Storage Blob Data Reader role](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#storage-blob-data-reader)" assigned? This role needs to be explicit assigned.

**Comment by flanakin** [comment] 2024-05-14 07:13
FYI - Arthur and I just ran thru this with @radut227 and the issue was that the Storage Blob Data Reader role wasn't assigned to the user who was loading data in Power BI. Please note you need at least one "Storage Blob Data" role even if you're a Reader, Contributor, or Owner on the storage account.

We do cover this in the docs, but we'll update it to be more explicit.

@devisaladi, can you also confirm if this helps you?

**Comment by devisaladi** [comment] 2024-05-14 14:16
@flanakin we added storage related account but still issue persists . can we have some one who can help us to setup this aptly so that we can save time . we have been working on it for a month . Got stuck , also we created microsfot ticket for help at the earliest . can you please guide us who can help us in saving time in setting this up 

Thanks
Devi

**Comment by devisaladi** [comment] 2024-05-14 20:55
![image](https://github.com/microsoft/finops-toolkit/assets/72529238/40e82cf7-da02-4d8e-9837-a214252c7ec5)

**Comment by arthurclares** [comment] 2024-05-14 21:07
@devisaladi This error message normally indicates that the storage account is empty. Can you go to the storage account and see if the msexport container has a .parquet file? 
If not, double check your cost exports are running fine and check if the data explorer pipelines are also working.  
Can you also confirm that adding the storage blob reader permissions to your storage fixed the "Access to resource is forbidden" issue?

**Comment by devisaladi** [comment] 2024-05-14 21:15
Can you also confirm that adding the storage blob reader permissions to your storage fixed the "Access to resource is forbidden" issue?

Yes the issue is gone after having storage blob reader role . 

-------------------------------------------------------------------------------------------

. Can you go to the storage account and see if the msexport container has a .parquet file?
please find the attached screenshot that has storage account is not empty 

![image](https://github.com/microsoft/finops-toolkit/assets/72529238/21bcd20f-1fff-4b4d-8b51-c1028c712fbc)

**Comment by paragbhardwaj1981** [comment] 2024-05-14 22:27
I believe we are missing the file .parquet. We have follow below steps and in Storage account we are seeing only .csv file. Any idea how to genrate .parquet file.
<img width="840" alt="image" src="https://github.com/microsoft/finops-toolkit/assets/71142051/d93ff389-6b8c-42ca-bafd-0d85370d06cf">

**Comment by flanakin** [comment] 2024-05-25 18:05
FYI - We spoke to @devisaladi and the primary issue there was the export was going to the `ingestion` container. Exports should be configured to go to the `msexports` container.

**Comment by flanakin** [comment] 2024-05-25 18:12
@paragbhardwaj1981 Try this:
1. Confirm that CSV files are getting exported into the `msexports` container. If not, update the Cost Management export configuration.
2. Confirm that the Microsoft.EventGrid resource provider is enabled on the subscription by going to Subscriptions > (your sub) > Settings > Resource providers and confirming Microsoft.EventGrid is set to "Registered". If not, register it from that screen.
3. Confirm the Data Factory trigger is started by going to Resource groups > (your hub RG) > (your Data Factory resource) > Launch Studio > Manage (toolbox icon) > Triggers and confirming all triggers are started. If not, click the Play icon for the trigger(s) and then click the "Publish all" button at the top. Confirm that finishes publishing successfully.
4. Re-run Cost Management exports. You can also run exports for previous months either from the portal or using the [Start-FinOpsCostExports command](https://aka.ms/ftk/Start-FinOpsCostExports).

**Comment by flanakin** [comment] 2024-06-05 07:15
@paragbhardwaj1981 any updates? Were you able to get past this? If not, we should setup a call to get you unblocked.

**Comment by arthurclares** [comment] 2024-06-19 12:47
Closing this as we already had a call with the customer.

**Closed by arthurclares** 2024-06-19 12:47 UTC
Labels: Needs: Triage 🔍, Area: Power BI, Needs: Attention 👋
